services:
  nfs-server:
    build:
      context: docker
      dockerfile: Dockerfile.server
    container_name: nfs-server
    privileged: true
    volumes:
      - nfs-data:/exports
    networks:
      nfsnet:
        ipv4_address: 192.168.100.10

  nfs-client:
    build:
      context: docker
      dockerfile: Dockerfile.client
    container_name: nfs-client
    privileged: true
    depends_on:
      - nfs-server
    networks:
      nfsnet:
        ipv4_address: 192.168.100.20
    command: sleep infinity

volumes:
  nfs-data:

networks:
  nfsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
