FROM ubuntu:22.04

RUN apt-get update -qq && \
    apt-get install -y -qq nfs-ganesha nfs-ganesha-vfs rpcbind dbus && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /exports && chmod 777 /exports

COPY ganesha.conf /etc/ganesha/ganesha.conf
COPY entrypoint-server.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 111/tcp 111/udp 2049/tcp 2049/udp

ENTRYPOINT ["/entrypoint.sh"]
